# Generated by Django 4.2.11 on 2024-05-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20000)),
                ('last_name', models.CharField(max_length=20000)),
                ('username', models.CharField(max_length=20000)),
            ],
        ),
    ]
