# Generated by Django 4.2.11 on 2024-05-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_uz',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_uz',
            field=models.TextField(null=True),
        ),
    ]
