# Generated by Django 4.2.11 on 2024-05-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aboutus',
        ),
    ]
