# Generated by Django 4.2.11 on 2024-05-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='banner',
        ),
    ]
