# Generated by Django 4.2.11 on 2024-05-28 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_fotogallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotogallery',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='fotogallery',
            name='name_ru',
            field=models.CharField(max_length=9000, null=True),
        ),
        migrations.AddField(
            model_name='fotogallery',
            name='name_uz',
            field=models.CharField(max_length=9000, null=True),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=9000, null=True)),
                ('name_en', models.CharField(max_length=9000, null=True)),
                ('name_ru', models.CharField(max_length=9000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Subcategoryimg')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
