# Generated by Django 4.2.11 on 2024-05-30 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_name_fotogallery_name_en_fotogallery_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
        ),
    ]
