# Generated by Django 4.2.11 on 2024-05-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_rename_category_subcategory_categoryu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='categoryu',
            new_name='category',
        ),
    ]
